### ISSUE TITLE
Process Team Work Feedback Audit 1

### ISSUE THREAD

**Issue by finn-mcclusky** [24-S2-2-C-EduKATE/24-S2-2-C-EduKATE.github.io#21]

**Comment by Evie-YW** [comment]
The team has great engagement and communication skills, but there are areas in which it can improve its meetings and online tools' utilization.

The constant full attendance at meetings is an indication of the team’s commitment as well as fostering an atmosphere of teamwork. This level of engagement is essential because it ensures effective task distribution in line with the project’s objectives. Another strength of the team lies in their ability to communicate easily; facilitating smooth operations and synchronised efforts towards common targets.

However, feedback indicates that more proactive participation is needed during meetings. More voices need to be heard from each member including the shyest among them – thus stimulating richer discussions and richer decisions. Nonetheless, meeting strategies could be improved through Round robin sharing or structured brainstorming sessions.

Also, while Slack, Microsoft Teams, and Trello are among the modern tools being used by the team; they still want to make maximum use of them for effective communication and project management particularly for remote or hybrid working environments used these days. Improved use of these tools could facilitate better updates, task management as well as ensuring every person stays informed.
